host: localhost # Hostname of mongodb
port: 27017 # Port of mongodb
login: root # Login of mongodb
password: root # Password of mongodb
database: Game # Database name
users:
  collection: users # Collection name for users
games:
  collection: games # Collection name for games